/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.default-controls[_ngcontent-%COMP%]{display:flex}.default-controls[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]{margin-right:40px}.main-controls[_ngcontent-%COMP%]{display:flex}.main-controls[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] + div[_ngcontent-%COMP%]{margin-left:20px}.sidebar-controls[_ngcontent-%COMP%]{display:flex}.cg-header-left[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]{margin-right:50px}.cg-body[_ngcontent-%COMP%]{display:flex}.cg-main-content[_ngcontent-%COMP%]{flex-grow:1}.cg-items[_ngcontent-%COMP%]{padding:.5vw;font-size:0;display:-ms-flexbox;-ms-flex-wrap:wrap;-ms-flex-direction:column;-webkit-flex-flow:row wrap;flex-flow:row wrap;display:-webkit-box;display:flex}.cg-items[_ngcontent-%COMP%]   .cg-item[_ngcontent-%COMP%]{position:relative;-webkit-box-flex:auto;-ms-flex:auto;flex-grow:.20;width:200px;height:145px;overflow:hidden;margin:.5vw}img[_ngcontent-%COMP%]{width:100%;height:auto}@media screen and (max-width:400px){.cg-items[_ngcontent-%COMP%]   .cg-item[_ngcontent-%COMP%]{margin:0}.cg-items[_ngcontent-%COMP%]{padding:0}}'];