/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/gallery/view-content/view-content.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../src/app/app.service';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '../../../../../src/app/services/content-service.service';
import * as import12 from './view-content.component.css.shim.ngstyle';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../../../../src/app/gallery/view-content/content-item-tile/content-item-tile.component';
import * as import15 from './content-item-tile/content-item-tile.component.ngfactory';
import * as import16 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory';
import * as import17 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '../../../../../src/app/gallery/view-content/content-details-sidebar/content-details-sidebar.component';
import * as import19 from './content-details-sidebar/content-details-sidebar.component.ngfactory';
import * as import20 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown';
import * as import25 from '@angular/common/src/directives/ng_for';
export class Wrapper_ViewContentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ViewContentComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ViewContentComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  check_categories(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.categories = currValue;
      this._expr_0 = currValue;
    }
  }
  check_contentItems(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.contentItems = currValue;
      this._expr_1 = currValue;
    }
  }
  check_themes(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.themes = currValue;
      this._expr_2 = currValue;
    }
  }
  check_countries(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.countries = currValue;
      this._expr_3 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ViewContentComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ViewContentComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ViewContentComponent>;
  _ViewContentComponent_0_3:Wrapper_ViewContentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ViewContentComponent_Host0,renderType_ViewContentComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'view-content',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ViewContentComponent0(this.viewUtils,this,0,this._el_0);
    this._ViewContentComponent_0_3 = new Wrapper_ViewContentComponent(this.injectorGet(import9.AppState,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.ContentService,this.parentIndex));
    this.compView_0.create(this._ViewContentComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ViewContentComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ViewContentComponent) && (0 === requestNodeIndex))) { return this._ViewContentComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ViewContentComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ViewContentComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ViewContentComponentNgFactory:import8.ComponentFactory<import0.ViewContentComponent> = new import8.ComponentFactory<import0.ViewContentComponent>('view-content',View_ViewContentComponent_Host0,import0.ViewContentComponent);
const styles_ViewContentComponent:any[] = [import12.styles];
class View_ViewContentComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_ViewContentComponent1,renderType_ViewContentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.index;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementAttribute(this._el_0,'index',((currVal_2 == null)? (null as any): currVal_2.toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ViewContentComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_ViewContentComponent2,renderType_ViewContentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.index;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementAttribute(this._el_0,'index',((currVal_2 == null)? (null as any): currVal_2.toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ViewContentComponent3 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import14.ContentItemTile>;
  _ContentItemTile_0_3:import15.Wrapper_ContentItemTile;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_ViewContentComponent3,renderType_ViewContentComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','cg-item','content-item-tile',''),(null as any));
    this.compView_0 = new import15.View_ContentItemTile0(this.viewUtils,this,0,this._el_0);
    this._ContentItemTile_0_3 = new import15.Wrapper_ContentItemTile(this.parentView.parentView.injectorGet(import9.AppState,this.parentView.parentIndex));
    this.compView_0.create(this._ContentItemTile_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'setSelected',(null as any)),this.eventHandler(this.handleEvent_0));
    this._ContentItemTile_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ContentItemTile) && (0 === requestNodeIndex))) { return this._ContentItemTile_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._ContentItemTile_0_3.check_data(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.selection;
    this._ContentItemTile_0_3.check_selection(currVal_0_0_1,throwOnChange,false);
    this._ContentItemTile_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ContentItemTile_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'setSelected')) {
      const pd_sub_0:any = ((<any>this.parentView.context.setSelectedItem($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ViewContentComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_ViewContentComponent,{});
export class View_ViewContentComponent0 extends import2.AppView<import0.ViewContentComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _NgbDropdown_30_3:import16.Wrapper_NgbDropdown;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _NgbDropdownToggle_34_3:import16.Wrapper_NgbDropdownToggle;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _vc_39:import13.ViewContainer;
  _TemplateRef_39_5:any;
  _NgFor_39_6:import17.Wrapper_NgFor;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _NgbDropdown_43_3:import16.Wrapper_NgbDropdown;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _NgbDropdownToggle_47_3:import16.Wrapper_NgbDropdownToggle;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _vc_52:import13.ViewContainer;
  _TemplateRef_52_5:any;
  _NgFor_52_6:import17.Wrapper_NgFor;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _NgbDropdown_56_3:import16.Wrapper_NgbDropdown;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _NgbDropdownToggle_60_3:import16.Wrapper_NgbDropdownToggle;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _anchor_92:any;
  /*private*/ _vc_92:import13.ViewContainer;
  _TemplateRef_92_5:any;
  _NgFor_92_6:import17.Wrapper_NgFor;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  compView_100:import2.AppView<import18.ContentDetailsSidebar>;
  _ContentDetailsSidebar_100_3:import19.Wrapper_ContentDetailsSidebar;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_123:any;
  /*private*/ _expr_124:any;
  /*private*/ _expr_125:any;
  /*private*/ _expr_126:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ViewContentComponent0,renderType_ViewContentComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_123 = import1.UNINITIALIZED;
    this._expr_124 = import1.UNINITIALIZED;
    this._expr_125 = import1.UNINITIALIZED;
    this._expr_126 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Content Gallery',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','content-gallery'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','cg-header flex-corner'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','cg-header-left flex-corner'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','main-controls'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'Button',new import3.InlineArray2(2,'class','btn btn-success'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-plus'),(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_13,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'Button',new import3.InlineArray2(2,'class','btn btn-danger'),(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-trash'),(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','default-controls'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray4(4,'class','dropdown-select','ngbDropdown',''),(null as any));
    this._NgbDropdown_30_3 = new import16.Wrapper_NgbDropdown(this.parentView.injectorGet(import20.NgbDropdownConfig,this.parentIndex));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_30,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Category:',(null as any));
    this._text_33 = this.renderer.createText(this._el_30,'\n                            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_30,'Button',new import3.InlineArray8(8,'aria-haspopup','true','class','btn btn-secondary dropdown-toggle','id','dropdownMenu1','ngbDropdownToggle',''),(null as any));
    this._NgbDropdownToggle_34_3 = new import16.Wrapper_NgbDropdownToggle(this._NgbDropdown_30_3.context,new import21.ElementRef(this._el_34));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_30,'\n                            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray4(4,'aria-labelledby','dropdownMenu1','class','dropdown-menu'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n                                ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._vc_39 = new import13.ViewContainer(39,37,this,this._anchor_39);
    this._TemplateRef_39_5 = new import22.TemplateRef_(this,39,this._anchor_39);
    this._NgFor_39_6 = new import17.Wrapper_NgFor(this._vc_39.vcRef,this._TemplateRef_39_5,this.parentView.injectorGet(import23.IterableDiffers,this.parentIndex),this.ref);
    this._text_40 = this.renderer.createText(this._el_37,'\n                            ',(null as any));
    this._text_41 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_28,'\n\n                        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray4(4,'class','dropdown-select','ngbDropdown',''),(null as any));
    this._NgbDropdown_43_3 = new import16.Wrapper_NgbDropdown(this.parentView.injectorGet(import20.NgbDropdownConfig,this.parentIndex));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_43,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Country:',(null as any));
    this._text_46 = this.renderer.createText(this._el_43,'\n                            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_43,'Button',new import3.InlineArray8(8,'aria-haspopup','true','class','btn btn-secondary dropdown-toggle','id','dropdownMenu2','ngbDropdownToggle',''),(null as any));
    this._NgbDropdownToggle_47_3 = new import16.Wrapper_NgbDropdownToggle(this._NgbDropdown_43_3.context,new import21.ElementRef(this._el_47));
    this._text_48 = this.renderer.createText(this._el_47,'',(null as any));
    this._text_49 = this.renderer.createText(this._el_43,'\n                            ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray4(4,'aria-labelledby','dropdownMenu2','class','dropdown-menu'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                                ',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_50,(null as any));
    this._vc_52 = new import13.ViewContainer(52,50,this,this._anchor_52);
    this._TemplateRef_52_5 = new import22.TemplateRef_(this,52,this._anchor_52);
    this._NgFor_52_6 = new import17.Wrapper_NgFor(this._vc_52.vcRef,this._TemplateRef_52_5,this.parentView.injectorGet(import23.IterableDiffers,this.parentIndex),this.ref);
    this._text_53 = this.renderer.createText(this._el_50,'\n                            ',(null as any));
    this._text_54 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._text_55 = this.renderer.createText(this._el_28,'\n\n                        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray4(4,'class','dropdown-select','ngbDropdown',''),(null as any));
    this._NgbDropdown_56_3 = new import16.Wrapper_NgbDropdown(this.parentView.injectorGet(import20.NgbDropdownConfig,this.parentIndex));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Sort By:',(null as any));
    this._text_59 = this.renderer.createText(this._el_56,'\n                            ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_56,'Button',new import3.InlineArray8(8,'aria-haspopup','true','class','btn btn-secondary dropdown-toggle','id','dropdownMenu3','ngbDropdownToggle',''),(null as any));
    this._NgbDropdownToggle_60_3 = new import16.Wrapper_NgbDropdownToggle(this._NgbDropdown_56_3.context,new import21.ElementRef(this._el_60));
    this._text_61 = this.renderer.createText(this._el_60,'',(null as any));
    this._text_62 = this.renderer.createText(this._el_56,'\n                            ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray4(4,'aria-labelledby','dropdownMenu3','class','dropdown-menu'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n                                ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Title',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n                                ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_63,'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Date Added',(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n                            ',(null as any));
    this._text_71 = this.renderer.createText(this._el_56,'\n                        ',(null as any));
    this._text_72 = this.renderer.createText(this._el_28,'\n\n                        ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_28,'button',new import3.InlineArray2(2,'class','btn btn-secondary'),(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_73,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_75 = this.renderer.createText(this._el_28,'\n\n                    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_11,'\n\n                ',(null as any));
    this._text_77 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','cg-header-right sidebar-controls'),(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'\n                    ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_78,'button',new import3.InlineArray2(2,'class','btn btn-secondary'),(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_80,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-info'),(null as any));
    this._text_82 = this.renderer.createText(this._el_78,'\n                ',(null as any));
    this._text_83 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_84 = this.renderer.createText(this._el_7,'\n\n            ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','cg-body'),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_85,'div',new import3.InlineArray2(2,'class','cg-main-content'),(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_87,'div',new import3.InlineArray2(2,'class','cg-items'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n                        ',(null as any));
    this._text_91 = this.renderer.createText(this._el_89,'\n\n                        ',(null as any));
    this._anchor_92 = this.renderer.createTemplateAnchor(this._el_89,(null as any));
    this._vc_92 = new import13.ViewContainer(92,89,this,this._anchor_92);
    this._TemplateRef_92_5 = new import22.TemplateRef_(this,92,this._anchor_92);
    this._NgFor_92_6 = new import17.Wrapper_NgFor(this._vc_92.vcRef,this._TemplateRef_92_5,this.parentView.injectorGet(import23.IterableDiffers,this.parentIndex),this.ref);
    this._text_93 = this.renderer.createText(this._el_89,'\n\n                        ',(null as any));
    this._text_94 = this.renderer.createText(this._el_89,'\n\n\n\n                        ',(null as any));
    this._text_95 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._text_96 = this.renderer.createText(this._el_87,'\n                ',(null as any));
    this._text_97 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_85,'div',new import3.InlineArray2(2,'class','cg-sidebar'),(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'\n                    ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_98,'content-details-sidebar',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_100 = new import19.View_ContentDetailsSidebar0(this.viewUtils,this,100,this._el_100);
    this._ContentDetailsSidebar_100_3 = new import19.Wrapper_ContentDetailsSidebar(this.parentView.injectorGet(import9.AppState,this.parentIndex));
    this.compView_100.create(this._ContentDetailsSidebar_100_3.context);
    this._text_101 = this.renderer.createText(this._el_98,'\n                ',(null as any));
    this._text_102 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._text_103 = this.renderer.createText(this._el_7,'\n\n\n        ',(null as any));
    this._text_104 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_30));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_34));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_37));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_43));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_47));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_50));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_56));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_60,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_60));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_65,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_65));
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_68,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_68));
    var disposable_10:Function = import3.subscribeToRenderElement(this,this._el_73,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_73));
    var disposable_11:Function = import3.subscribeToRenderElement(this,this._el_80,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_80));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._anchor_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.NgbDropdownToggle) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgbDropdownToggle_34_3.context; }
    if (((token === import22.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import25.NgFor) && (39 === requestNodeIndex))) { return this._NgFor_39_6.context; }
    if (((token === import24.NgbDropdown) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgbDropdown_30_3.context; }
    if (((token === import24.NgbDropdownToggle) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgbDropdownToggle_47_3.context; }
    if (((token === import22.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import25.NgFor) && (52 === requestNodeIndex))) { return this._NgFor_52_6.context; }
    if (((token === import24.NgbDropdown) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgbDropdown_43_3.context; }
    if (((token === import24.NgbDropdownToggle) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgbDropdownToggle_60_3.context; }
    if (((token === import24.NgbDropdown) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._NgbDropdown_56_3.context; }
    if (((token === import22.TemplateRef) && (92 === requestNodeIndex))) { return this._TemplateRef_92_5; }
    if (((token === import25.NgFor) && (92 === requestNodeIndex))) { return this._NgFor_92_6.context; }
    if (((token === import18.ContentDetailsSidebar) && (100 === requestNodeIndex))) { return this._ContentDetailsSidebar_100_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgbDropdown_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    this._NgbDropdownToggle_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_39_0_0:any = this.context.categories;
    this._NgFor_39_6.check_ngForOf(currVal_39_0_0,throwOnChange,false);
    this._NgFor_39_6.ngDoCheck(this,this._anchor_39,throwOnChange);
    this._NgbDropdown_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    this._NgbDropdownToggle_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_52_0_0:any = this.context.countries;
    this._NgFor_52_6.check_ngForOf(currVal_52_0_0,throwOnChange,false);
    this._NgFor_52_6.ngDoCheck(this,this._anchor_52,throwOnChange);
    this._NgbDropdown_56_3.ngDoCheck(this,this._el_56,throwOnChange);
    this._NgbDropdownToggle_60_3.ngDoCheck(this,this._el_60,throwOnChange);
    const currVal_92_0_0:any = this.context.contentItems;
    this._NgFor_92_6.check_ngForOf(currVal_92_0_0,throwOnChange,false);
    this._NgFor_92_6.ngDoCheck(this,this._anchor_92,throwOnChange);
    const currVal_100_0_0:any = this.context.sidebarVisible;
    this._ContentDetailsSidebar_100_3.check_visible(currVal_100_0_0,throwOnChange,false);
    const currVal_100_0_1:any = this.context.selection.contentItem;
    this._ContentDetailsSidebar_100_3.check_selectedItem(currVal_100_0_1,throwOnChange,false);
    this._ContentDetailsSidebar_100_3.ngDoCheck(this,this._el_100,throwOnChange);
    this._vc_39.detectChangesInNestedViews(throwOnChange);
    this._vc_52.detectChangesInNestedViews(throwOnChange);
    this._vc_92.detectChangesInNestedViews(throwOnChange);
    this._NgbDropdown_30_3.checkHost(this,this,this._el_30,throwOnChange);
    this._NgbDropdownToggle_34_3.checkHost(this,this,this._el_34,throwOnChange);
    const currVal_123:any = import3.inlineInterpolate(1,'',(((this.context.selection.category == null)? (null as any): this.context.selection.category.name) || 'Any'),'');
    if (import3.checkBinding(throwOnChange,this._expr_123,currVal_123)) {
      this.renderer.setText(this._text_35,currVal_123);
      this._expr_123 = currVal_123;
    }
    this._NgbDropdown_43_3.checkHost(this,this,this._el_43,throwOnChange);
    this._NgbDropdownToggle_47_3.checkHost(this,this,this._el_47,throwOnChange);
    const currVal_124:any = import3.inlineInterpolate(1,'',(((this.context.selection.country == null)? (null as any): this.context.selection.country.name) || 'All'),'');
    if (import3.checkBinding(throwOnChange,this._expr_124,currVal_124)) {
      this.renderer.setText(this._text_48,currVal_124);
      this._expr_124 = currVal_124;
    }
    this._NgbDropdown_56_3.checkHost(this,this,this._el_56,throwOnChange);
    this._NgbDropdownToggle_60_3.checkHost(this,this,this._el_60,throwOnChange);
    const currVal_125:any = import3.inlineInterpolate(1,'',(((this.context.selection.country == null)? (null as any): this.context.selection.country.name) || 'All'),'');
    if (import3.checkBinding(throwOnChange,this._expr_125,currVal_125)) {
      this.renderer.setText(this._text_61,currVal_125);
      this._expr_125 = currVal_125;
    }
    const currVal_126:any = import3.inlineInterpolate(1,'',(this.context.selection.sortAsc? 'fa fa-sort-alpha-asc': 'fa fa-sort-alpha-desc'),'');
    if (import3.checkBinding(throwOnChange,this._expr_126,currVal_126)) {
      this.renderer.setElementProperty(this._el_74,'className',currVal_126);
      this._expr_126 = currVal_126;
    }
    this.compView_100.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_39.destroyNestedViews();
    this._vc_52.destroyNestedViews();
    this._vc_92.destroyNestedViews();
    this.compView_100.destroy();
    this._NgbDropdown_30_3.ngOnDestroy();
    this._NgbDropdown_43_3.ngOnDestroy();
    this._NgbDropdown_56_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 39)) { return new View_ViewContentComponent1(this.viewUtils,this,39,this._anchor_39,this._vc_39); }
    if ((nodeIndex == 52)) { return new View_ViewContentComponent2(this.viewUtils,this,52,this._anchor_52,this._vc_52); }
    if ((nodeIndex == 92)) { return new View_ViewContentComponent3(this.viewUtils,this,92,this._anchor_92,this._vc_92); }
    return (null as any);
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_30_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_34_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.updateSelectedDropdownItem($event,'category')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_43_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_47_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.updateSelectedDropdownItem($event,'country')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_56_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_60(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_60_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_65(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.setSortBy($event,'name')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_68(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.setSortBy($event,'dateAdded')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_73(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.switchSort()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_80(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.toggleSidebar()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}