/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['body,html{height:100%;font-family:Arial,Helvetica,sans-serif}a.active{background-color:gray}'];