/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.active[_ngcontent-%COMP%]{color:#fff}.navbar-toggler[_ngcontent-%COMP%]{border:1px solid silver;border-radius:2px;color:#eee}'];