/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/common/header/header.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './header.component.css.shim.ngstyle';
import * as import9 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/router/src/router_state';
import * as import13 from '@angular/common/src/location/location_strategy';
import * as import14 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/router/src/directives/router_link';
import * as import17 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown';
export class Wrapper_HeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HeaderComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HeaderComponent>;
  _HeaderComponent_0_3:Wrapper_HeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'header',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderComponentNgFactory:import7.ComponentFactory<import0.HeaderComponent> = new import7.ComponentFactory<import0.HeaderComponent>('header',View_HeaderComponent_Host0,import0.HeaderComponent);
const styles_HeaderComponent:any[] = [import8.styles];
var renderType_HeaderComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_HeaderComponent,{});
export class View_HeaderComponent0 extends import1.AppView<import0.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import9.Wrapper_RouterLinkWithHref;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _RouterLinkWithHref_26_3:import9.Wrapper_RouterLinkWithHref;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _NgbDropdown_50_3:import10.Wrapper_NgbDropdown;
  _text_51:any;
  _el_52:any;
  _NgbDropdownToggle_52_3:import10.Wrapper_NgbDropdownToggle;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _arr_76:any;
  _arr_77:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent0,renderType_HeaderComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_76 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_77 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-light bg-faded navbar-toggleable-md'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray16(14,'aria-controls','navbarsExampleContainer','aria-expanded','false','aria-label','Toggle navigation','class','navbar-toggler navbar-toggler-right','data-target','#navbarsExampleContainer','data-toggle','collapse','type','button'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'class','navbar-toggler-icon'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'MyOralVillage',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbarsExampleContainer'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'ul',new import3.InlineArray2(2,'class','navbar-nav mr-auto'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'li',new import3.InlineArray2(2,'class','nav-item active'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'class','nav-link'),(null as any));
    this._RouterLinkWithHref_18_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import11.Router,this.parentIndex),this.parentView.injectorGet(import12.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import13.LocationStrategy,this.parentIndex));
    this._text_19 = this.renderer.createText(this._el_18,'Home ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'(current)',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n\n          ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_14,'li',new import3.InlineArray2(2,'class','nav-item'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'a',new import3.InlineArray2(2,'class','nav-link'),(null as any));
    this._RouterLinkWithHref_26_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import11.Router,this.parentIndex),this.parentView.injectorGet(import12.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import13.LocationStrategy,this.parentIndex));
    this._text_27 = this.renderer.createText(this._el_26,'Gallery ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_29 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_14,'\n\n          ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_14,'li',new import3.InlineArray2(2,'class','nav-item'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'a',new import3.InlineArray4(4,'class','nav-link','href','#'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Contact Us',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._text_36 = this.renderer.createText(this._el_14,'\n\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_12,'form',new import3.InlineArray2(2,'class','form-inline my-2 my-md-0'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'input',new import3.InlineArray8(6,'class','form-control mr-sm-2','placeholder','Search','type','text'),(null as any));
    this._text_41 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_38,'button',new import3.InlineArray4(4,'class','btn btn-outline-success my-2 my-sm-0','type','submit'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Search',(null as any));
    this._text_44 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_12,'ul',new import3.InlineArray2(2,'class','navbar-nav navbar-right'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n          ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'li',new import3.InlineArray2(2,'class','nav-item dropdown'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n            ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'ngbDropdown',''),(null as any));
    this._NgbDropdown_50_3 = new import10.Wrapper_NgbDropdown(this.parentView.injectorGet(import14.NgbDropdownConfig,this.parentIndex));
    this._text_51 = this.renderer.createText(this._el_50,'\n              ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'a',new import3.InlineArray8(8,'aria-haspopup','true','class','nav-link dropdown-toggle','id','dropdownMenu1','ngbDropdownToggle',''),(null as any));
    this._NgbDropdownToggle_52_3 = new import10.Wrapper_NgbDropdownToggle(this._NgbDropdown_50_3.context,new import15.ElementRef(this._el_52));
    this._text_53 = this.renderer.createText(this._el_52,'Preferences',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n              ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_50,'div',new import3.InlineArray4(4,'aria-labelledby','dropdownMenu1','class','dropdown-menu'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'\n                ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_55,'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Action',(null as any));
    this._text_59 = this.renderer.createText(this._el_55,'\n                ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_55,'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'Another Action',(null as any));
    this._text_62 = this.renderer.createText(this._el_55,'\n                ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_55,'button',new import3.InlineArray2(2,'class','dropdown-item'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Something else is here',(null as any));
    this._text_65 = this.renderer.createText(this._el_55,'\n              ',(null as any));
    this._text_66 = this.renderer.createText(this._el_50,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._text_68 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_12,'\n\n      ',(null as any));
    this._text_70 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_71 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_26));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_50));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_52));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import16.RouterLinkWithHref) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_26_3.context; }
    if (((token === import17.NgbDropdownToggle) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgbDropdownToggle_52_3.context; }
    if (((token === import17.NgbDropdown) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NgbDropdown_50_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_18_0_0:any = this._arr_76('./home');
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_26_0_0:any = this._arr_77('./gallery');
    this._RouterLinkWithHref_26_3.check_routerLink(currVal_26_0_0,throwOnChange,false);
    this._RouterLinkWithHref_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgbDropdown_50_3.ngDoCheck(this,this._el_50,throwOnChange);
    this._NgbDropdownToggle_52_3.ngDoCheck(this,this._el_52,throwOnChange);
    this._RouterLinkWithHref_18_3.checkHost(this,this,this._el_18,throwOnChange);
    this._RouterLinkWithHref_26_3.checkHost(this,this,this._el_26,throwOnChange);
    this._NgbDropdown_50_3.checkHost(this,this,this._el_50,throwOnChange);
    this._NgbDropdownToggle_52_3.checkHost(this,this,this._el_52,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_18_3.ngOnDestroy();
    this._RouterLinkWithHref_26_3.ngOnDestroy();
    this._NgbDropdown_50_3.ngOnDestroy();
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_26_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_50_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_52_3.handleEvent(eventName,$event) && result);
    return result;
  }
}