/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/login-signup/login/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/app.service';
import * as import9 from './login.component.css.shim.ngstyle';
import * as import10 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/control_container';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'login',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.AppState,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('login',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = [import9.styles];
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _NgForm_25_3:import10.Wrapper_NgForm;
  _ControlContainer_25_4:any;
  _NgControlStatusGroup_25_5:import11.Wrapper_NgControlStatusGroup;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','mainbox col-md-4 offset-md-4 col-sm-8 offset-sm-2','id','loginbox'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','card'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','card-header'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','login-header'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Sign In',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_15,'a',new import3.InlineArray2(2,'href',''),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Forgot password?',(null as any));
    this._text_18 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-12'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'form',new import3.InlineArray4(4,'class','form-horizontal','role','form'),(null as any));
    this._NgForm_25_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_25_4 = this._NgForm_25_3.context;
    this._NgControlStatusGroup_25_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_25_4);
    this._text_26 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','form-group form-group-lg'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n\n                                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'label',new import3.InlineArray4(4,'class','control-label','for','username'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Username',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                                ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'span',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                                        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-user'),(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n                                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_32,'input',new import3.InlineArray16(12,'class','form-control','id','username','name','username','placeholder','Enter Username','type','text','value',''),(null as any));
    this._text_38 = this.renderer.createText(this._el_27,'\n\n                            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','form-group form-group-lg'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n\n                                ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'label',new import3.InlineArray4(4,'class','control-label','for','password'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Password',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_40,'span',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_45,'span',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                                        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-lock'),(null as any));
    this._text_49 = this.renderer.createText(this._el_46,'\n                                ',(null as any));
    this._text_50 = this.renderer.createText(this._el_45,'\n                                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_45,'input',new import3.InlineArray16(12,'class','form-control','id','password','name','password','placeholder','Password','type','text','value',''),(null as any));
    this._text_52 = this.renderer.createText(this._el_40,'\n\n                            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','text-center control-button col-sm-12'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Sign In',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'\n                                ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'div',new import3.InlineArray2(2,'class','text-bottom'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n                                    ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Don\'t have an account ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'a',new import3.InlineArray4(4,'class','margin-left','href','#'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'Sign Up Here',(null as any));
    this._text_68 = this.renderer.createText(this._el_62,'\n                                ',(null as any));
    this._text_69 = this.renderer.createText(this._el_60,'\n                            ',(null as any));
    this._text_70 = this.renderer.createText(this._el_25,'\n                        ',(null as any));
    this._text_71 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_73 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_74 = this.renderer.createText(this._el_4,'\n\n\n        ',(null as any));
    this._text_75 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_25));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.NgForm) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._NgForm_25_3.context; }
    if (((token === import13.ControlContainer) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._ControlContainer_25_4; }
    if (((token === import14.NgControlStatusGroup) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._NgControlStatusGroup_25_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatusGroup_25_5.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatusGroup_25_5.checkHost(this,this,this._el_25,throwOnChange);
  }
  destroyInternal():void {
    this._NgForm_25_3.ngOnDestroy();
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_25_3.handleEvent(eventName,$event) && result);
    return result;
  }
}