/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['img[_ngcontent-%COMP%]{width:100%;height:auto}.cg-item-inner[_ngcontent-%COMP%]   .cg-item-info[_ngcontent-%COMP%]{display:none;text-align:center;font-size:16px;position:absolute;height:15%;width:100%;bottom:-2px;background:hsla(0,0%,100%,.72)}.selected-item[_ngcontent-%COMP%]{border:3px solid red}.cg-item-inner[_ngcontent-%COMP%]:hover   .cg-item-info[_ngcontent-%COMP%]{display:block}'];