/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/gallery/view-categories/view-categories.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/app.service';
import * as import9 from './view-categories.component.css.shim.ngstyle';
export class Wrapper_ViewCategoriesComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ViewCategoriesComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ViewCategoriesComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ViewCategoriesComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ViewCategoriesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ViewCategoriesComponent>;
  _ViewCategoriesComponent_0_3:Wrapper_ViewCategoriesComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ViewCategoriesComponent_Host0,renderType_ViewCategoriesComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'view-categories',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ViewCategoriesComponent0(this.viewUtils,this,0,this._el_0);
    this._ViewCategoriesComponent_0_3 = new Wrapper_ViewCategoriesComponent(this.injectorGet(import8.AppState,this.parentIndex));
    this.compView_0.create(this._ViewCategoriesComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ViewCategoriesComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ViewCategoriesComponent) && (0 === requestNodeIndex))) { return this._ViewCategoriesComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ViewCategoriesComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ViewCategoriesComponentNgFactory:import7.ComponentFactory<import0.ViewCategoriesComponent> = new import7.ComponentFactory<import0.ViewCategoriesComponent>('view-categories',View_ViewCategoriesComponent_Host0,import0.ViewCategoriesComponent);
const styles_ViewCategoriesComponent:any[] = [import9.styles];
var renderType_ViewCategoriesComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ViewCategoriesComponent,{});
export class View_ViewCategoriesComponent0 extends import1.AppView<import0.ViewCategoriesComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ViewCategoriesComponent0,renderType_ViewCategoriesComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container gallery'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-md-3'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','card'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'img',new import3.InlineArray8(6,'alt','Card image cap','class','card-img-top','src','https://www.smashingmagazine.com/wp-content/uploads/2016/05/better-icon-design-preview-opt.png'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'h4',new import3.InlineArray2(2,'class','card-title'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Designs & Wireframes',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'p',new import3.InlineArray2(2,'class','card-text'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Some quick example text to build on the>Designs & Wireframes and make up the bulk of the card\'s\n                            content.\n                        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_6,'ul',new import3.InlineArray2(2,'class','list-group list-group-flush'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'li',new import3.InlineArray2(2,'class','list-group-item'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Cras justo odio',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray4(4,'class','card-link','href','#'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Card link',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-md-3'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'div',new import3.InlineArray2(2,'class','card'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'img',new import3.InlineArray8(6,'alt','Card image cap','class','card-img-top','src','https://udemy-images.udemy.com/course/750x422/145178_5bb8_3.jpg'),(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'h4',new import3.InlineArray2(2,'class','card-title'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Reports',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_39,'p',new import3.InlineArray2(2,'class','card-text'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Some quick example text to build on the card title and make up the bulk of the card\'s content.',(null as any));
    this._text_46 = this.renderer.createText(this._el_39,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_35,'ul',new import3.InlineArray2(2,'class','list-group list-group-flush'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'li',new import3.InlineArray2(2,'class','list-group-item'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'Cras justo odio',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_53 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'a',new import3.InlineArray4(4,'class','card-link','href','#'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Card link',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                ',(null as any));
    this._text_59 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-md-3'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n            ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'div',new import3.InlineArray2(2,'class','card'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'img',new import3.InlineArray8(6,'alt','Card image cap','class','card-img-top','src','https://udemy-images.udemy.com/course/750x422/145178_5bb8_3.jpg'),(null as any));
    this._text_67 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_64,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n                    ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'h4',new import3.InlineArray2(2,'class','card-title'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'Media',(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n                    ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_68,'p',new import3.InlineArray2(2,'class','card-text'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Some quick example of the card\'s content.',(null as any));
    this._text_75 = this.renderer.createText(this._el_68,'\n                ',(null as any));
    this._text_76 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_64,'ul',new import3.InlineArray2(2,'class','list-group list-group-flush'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'\n                    ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_77,'li',new import3.InlineArray2(2,'class','list-group-item'),(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'Photos',(null as any));
    this._text_81 = this.renderer.createText(this._el_77,'\n                    ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_77,'li',new import3.InlineArray2(2,'class','list-group-item'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'Videos',(null as any));
    this._text_84 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._text_85 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_64,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'\n                    ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_86,'a',new import3.InlineArray4(4,'class','card-link','href','#'),(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'Card link',(null as any));
    this._text_90 = this.renderer.createText(this._el_86,'\n                    ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_86,'a',new import3.InlineArray4(4,'class','card-link','href','#'),(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'Another link',(null as any));
    this._text_93 = this.renderer.createText(this._el_86,'\n                ',(null as any));
    this._text_94 = this.renderer.createText(this._el_64,'\n            ',(null as any));
    this._text_95 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._text_96 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_97 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_98 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._text_98
    ]
    ),(null as any));
    return (null as any);
  }
}